// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/phish-variants/CrimsonOps.tsx": () => import("../components/mockups/phish-variants/CrimsonOps.tsx"),
  "./components/mockups/phish-variants/MatrixRain.tsx": () => import("../components/mockups/phish-variants/MatrixRain.tsx"),
  "./components/mockups/phish-variants/SynthwaveGrid.tsx": () => import("../components/mockups/phish-variants/SynthwaveGrid.tsx")
};
